<?php

namespace MODELS;

require_once(__DIR__ . '/../../DATABASE/Connection.php');

use DATABASE\Connection;
use Exception;
use mysqli_sql_exception;

class Group
{
    private $id;
    private $madeBy;
    private $nama;
    private $deskripsi;
    private $tanggalDibuat;
    private $jenis; 
    private $kode;
    private $listMember;
    private $listThread;

    // ... [Keep your existing Constructor, Getters, and Setters here] ...
    // I will assume the Constructor, Getters, and Setters are unchanged from your code
    // but remember that the Constructor expects 9 arguments.

    public function __construct($id, $madeBy, $nama, $deskripsi, $tanggalDibuat, $jenis, $kode, $listMember, $listThread)
    {
        // (You can temporarily relax the setId check if you want to allow ID=0 for new objects before insertion)
        $this->id = $id; 
        $this->setMadeBy($madeBy);
        $this->setNama($nama);
        $this->setDeskripsi($deskripsi);
        $this->setTanggalDibuat($tanggalDibuat);
        $this->setJenis($jenis);
        $this->setKode($kode);
        $this->setListMember($listMember);
        $this->setListThread($listThread);
    }

    // ... [Keep your existing Filter functions here] ...

    // ==========================================================================
    // DATABASE FUNCTIONS
    // ==========================================================================

    public function insert_group_to_database()
    {
        // 1. Corrected SQL: Changed dot (.) to comma (,) between deskripsi and tanggal
        $sql = "INSERT INTO `grup` 
                (`username_pembuat`, `nama`, `deskripsi`, `tanggal_pembentukan`, `jenis`, `kode_pendaftaran`) 
                VALUES (?, ?, ?, ?, ?, ?)";

        try {
            Connection::startConnection();
            $conn = Connection::getConnection();
            $stmt = $conn->prepare($sql);

            if ($stmt === false) {
                throw new Exception("Gagal prepare statement: " . $conn->error);
            }

            // 2. Binding: 'ssssss' means 6 Strings
            $stmt->bind_param(
                'ssssss', 
                $this->madeBy, 
                $this->nama, 
                $this->deskripsi, 
                $this->tanggalDibuat, 
                $this->jenis, 
                $this->kode
            );

            $stmt->execute();

            // 3. Get the new ID generated by Database and update this object
            if ($stmt->affected_rows > 0) {
                $this->id = $stmt->insert_id;
            } else {
                throw new Exception("Gagal insert data. Tidak ada baris yang terpengaruh.");
            }

            $stmt->close();

        } catch (Exception $e) {
            throw $e;
        } finally {
            // Keep connection handling consistent with your architecture
            if (Connection::getConnection() !== null) {
                Connection::closeConnection();
            }
        }
    }

    // ==========================================================================
    // STATIC SEARCH FUNCTIONS
    // ==========================================================================

    /**
     * Mencari Group berdasarkan ID
     * @param int $id
     * @return Group|null Mengembalikan objek Group atau null jika tidak ketemu
     */
    public static function getGroupById($id)
    {
        $sql = "SELECT * FROM `grup` WHERE `id` = ?";
        $groupObj = null;

        try {
            Connection::startConnection();
            $conn = Connection::getConnection();
            $stmt = $conn->prepare($sql);
            $stmt->bind_param('i', $id); // 'i' for integer
            $stmt->execute();
            
            $result = $stmt->get_result();

            if ($row = $result->fetch_assoc()) {
                // Create new instance using DB data
                // Note: passing [] for lists because DB fetch doesn't automatically join members
                $groupObj = new Group(
                    $row['id'],
                    $row['username_pembuat'],
                    $row['nama'],
                    $row['deskripsi'],
                    $row['tanggal_pembentukan'],
                    $row['jenis'],
                    $row['kode_pendaftaran'],
                    [], // listMember kosong default
                    []  // listThread kosong default
                );
            }
            $stmt->close();
            return $groupObj;

        } catch (Exception $e) {
            throw $e;
        } finally {
            Connection::closeConnection();
        }
    }

    /**
     * Mencari Group berdasarkan Nama (Search / LIKE)
     * @param string $keyword
     * @return array Array of Group objects
     */
    public static function getGroupsByName($keyword)
    {
        // Menggunakan LIKE untuk pencarian parsial (misal: "Program" akan menemukan "Programming")
        $sql = "SELECT * FROM `grup` WHERE `nama` LIKE ?";
        $listGroups = [];
        $searchTerm = "%" . $keyword . "%";

        try {
            Connection::startConnection();
            $conn = Connection::getConnection();
            $stmt = $conn->prepare($sql);
            $stmt->bind_param('s', $searchTerm);
            $stmt->execute();
            
            $result = $stmt->get_result();

            while ($row = $result->fetch_assoc()) {
                $listGroups[] = new Group(
                    $row['id'],
                    $row['username_pembuat'],
                    $row['nama'],
                    $row['deskripsi'],
                    $row['tanggal_pembentukan'],
                    $row['jenis'],
                    $row['kode_pendaftaran'],
                    [], 
                    []  
                );
            }
            $stmt->close();
            return $listGroups;

        } catch (Exception $e) {
            throw $e;
        } finally {
            Connection::closeConnection();
        }
    }
}